-- Migration: 002_core_schema.sql
-- Description: Core database schema for Habiter (TICKET-003).
-- Creates the habits, categories, checkins, daily_logs, and settings tables
-- exactly as specified in the Technical Architecture Document Section 3.
--
-- Conventions:
--   * IDs are TEXT UUIDs (generated by the app layer), not integer autoincrement.
--   * BOOLEAN columns are stored as INTEGER 0/1 (SQLite has no native boolean).
--   * DATETIME columns default to SQLite's current UTC timestamp.
--   * Enumerated columns (frequency_type, status) get CHECK constraints so bad
--     values are rejected at the database layer.

-- ============================================================
-- categories — user-defined groupings for habits.
-- Referenced by habits.category_id.
-- ============================================================
CREATE TABLE IF NOT EXISTS categories (
  id         TEXT PRIMARY KEY,                       -- UUID
  name       TEXT NOT NULL,
  color      TEXT,                                   -- hex color used as the category tag
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- habits — each habit the user has created.
-- category_id is nullable: a habit may be uncategorized.
-- ON DELETE SET NULL keeps the habit (and its history) when its
-- category is deleted (TICKET-007 behavior: reassign or uncategorize).
-- ============================================================
CREATE TABLE IF NOT EXISTS habits (
  id              TEXT PRIMARY KEY,                  -- UUID
  name            TEXT NOT NULL,
  icon            TEXT,                              -- emoji or icon key
  category_id     TEXT REFERENCES categories(id) ON DELETE SET NULL,
  frequency_type  TEXT NOT NULL
                  CHECK (frequency_type IN ('daily', 'specific_days', 'times_per_week')),
  frequency_value TEXT,                              -- JSON: '["mon","wed","fri"]' or '{"count":3}'
  reminder_time   TEXT,                              -- local time "HH:MM", nullable
  is_archived     INTEGER NOT NULL DEFAULT 0
                  CHECK (is_archived IN (0, 1)),     -- BOOLEAN: archived habits keep history
  sort_order      INTEGER NOT NULL DEFAULT 0,        -- controls grid display order
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- checkins — one row per habit per day; the core data of the app.
-- Unique on (habit_id, date): a habit has exactly one status per day.
-- ON DELETE CASCADE removes a habit's check-ins with it
-- (TICKET-006 behavior: permanent delete removes the habit and its check-ins).
-- ============================================================
CREATE TABLE IF NOT EXISTS checkins (
  id         TEXT PRIMARY KEY,                       -- UUID
  habit_id   TEXT NOT NULL REFERENCES habits(id) ON DELETE CASCADE,
  date       TEXT NOT NULL,                          -- ISO date 'YYYY-MM-DD'
  status     TEXT NOT NULL
             CHECK (status IN ('completed', 'partial', 'not_done', 'skipped')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE (habit_id, date)
);

-- Day-scoped lookups (daily progress chart, mood strip) query all
-- check-ins for a given date, so index by date as well as by habit.
CREATE INDEX IF NOT EXISTS idx_checkins_date ON checkins(date);

-- ============================================================
-- daily_logs — mood and sleep, which are day-level (not per-habit).
-- Unique on date: one row per calendar day.
-- ============================================================
CREATE TABLE IF NOT EXISTS daily_logs (
  id          TEXT PRIMARY KEY,                      -- UUID
  date        TEXT NOT NULL UNIQUE,                  -- ISO date 'YYYY-MM-DD'
  mood        TEXT,                                  -- 'great'|'good'|'neutral'|'bad'|'terrible', nullable
  sleep_hours REAL,                                  -- e.g. 7.5, nullable
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- settings — simple key-value store for app-level preferences.
-- ============================================================
CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
